### ISSUE TITLE
cannot create group chat

### ISSUE THREAD

**Issue by andrewvdp** [daopanel/relay#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot create a group chat
<img width="457" alt="Screen Shot 2022-07-13 at 2 42 08 PM" src="https://user-images.githubusercontent.com/5456408/178841776-47bddd64-123c-4700-add3-f7d36400ff5c.png">
<img width="543" alt="Screen Shot 2022-07-13 at 2 42 15 PM" src="https://user-images.githubusercontent.com/5456408/178841792-4af87d9d-e0e5-4b86-b5ac-587e6ae26196.png">

### Expected Behavior

I should be able to create a group chat

### Steps To Reproduce

click the icon in the top right on `/groups` to create a group chat -> enter two ens names -> click "create group"

**Comment by killthebuddh4** [comment]
@andrewvdp If you use an address I think it will work.

**Comment by andrewvdp** [comment]
> @andrewvdp If you use an address I think it will work.



> @andrewvdp If you use an address I think it will work.

still getting the same issue
